eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/thinkphp?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
  application:
    name: service-handle

mybatis:
  typeAliasesPackage: ee.java2.handle.bean
  mapperLocations: classpath:mapper/*.xml
