eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: service-routegateway
zuul:
  routes:
    sf:
      path: /api/sfa/sf/**
      serviceId: service-interaction
    ssf: